-- Run this in your Supabase SQL Editor
-- Updated schema with metadata support

create table if not exists analysis_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  file_name text,
  file_type text,
  score int,
  risk_level text,
  summary text,
  metadata jsonb  -- stores the full ffprobe metadata as JSON
);

-- Enable Row Level Security
alter table analysis_logs enable row level security;

-- Allow public read access (for demo)
create policy "Allow public read access"
  on analysis_logs for select
  using ( true );

-- Allow public insert access (for demo — secure this in production!)
create policy "Allow public insert access"
  on analysis_logs for insert
  with check ( true );
